### ISSUE TITLE
Feature Request: Assign Group Code etc for current members

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-group-accounts#20]
Provide functionality for giving a Group Code to existing members who have the Level.
This would be for active sites that add Group Add On.
Right now, current members would have to check gain to get a Group Code for a child user.

We have a code recipe that did this for the Sponsor Plugin
https://gist.github.com/dparker1005/b810ed3989242100de46efa661210c26

**Comment by MaryOJob** [comment]
Another Request (Moderators Only): [#546485]

**Comment by kimwhite** [comment]
another need 562575
